[package]
name = "globaldata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
icu_provider = { path = "../../provider/core" }
icu_locid = { path = "../../components/locid" }

[features]
custom_data = []
all_features_hack = []
