[package]
name = "serde_unaligned"
version = "0.1.0"
authors = ["Shane F. Carr <shane@unicode.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
icu_benchmark_macros = { version = "0.1", path = "../../tools/benchmark/macros" }
criterion = "0.3.3"
iai = "0.1"

[features]
benchmark_memory = ["icu_benchmark_macros/benchmark_memory"]
bench = []

[[bench]]
name = "uvec"
harness = false

[[bench]]
name = "uvec_iai"
harness = false
