# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "hashcmp"
description = "Hash function comparisons"
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.workspaces]
independent = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
t1ha = "0.1.0"
wyhash = "0.5.0"
twox-hash = "1.6.3"
xxhash-rust = { version = "0.8.7", features = ["xxh64", "xxh32", "xxh3"] }
crc32fast = "1.3"

[dev-dependencies]
